### ISSUE TITLE
档案查询用不了

### ISSUE THREAD

**Issue by Blackwithking** [MX233/MCInfoPlugin#4]
现在这个档案查询用不了，是否是java版账号已经全转移的原因？

**Comment by Pmaru-top** [comment]
请提供更多信息
例如 
 输入status命令是否显示这个插件被加载
 插件版本

**Comment by Blackwithking** [comment]
插件已经被加载V1.1版本，查询到的皮肤都为史蒂夫、艾利克斯.不是正版账号对应的皮肤

**Comment by Pmaru-top** [comment]
> 插件已经被加载V1.1版本，查询到的皮肤都为史蒂夫、艾利克斯.不是正版账号对应的皮肤

可能是第三方api的问题，我测试了我的正版名称是正确显示的
